name: First workflow
on:
  push:
    branches: 
      - main
      - dev/**
      - dev*
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  compilation-work:
    runs-on: ubuntu-20.04
    steps:
      - name: Get code first 
        uses: actions/checkout@v3
      - name: Initial check
        run: | 
          pwd
          ls -la
          date "+DATE: %D, TIME: %T"
      - name: Execute C code
        run: |
          gcc *.c -o Output
      - name: Check artifact
        run: ls -la
      - name: Get output
        run: ./Output
      - name: Upload compiled Artifact
        uses: actions/upload-artifact@v3
        with:
          name: C-artifact
          path: | 
            Output
            *.c

  reuse-artifact:
    needs: compilation-work
    runs-on: ubuntu-22.04
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: C-artifact
      - name: Check 
        run: ls -la 
      - name: Show Output
        run: ./Output
        
